services:
  - type: web
    name: navi-3d-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: navi-3d-db
          property: connectionString

databases:
  - name: navi-3d-db
    plan: free
    databaseName: navi3d
    user: navi3d_user
